# Generated by Django 5.1.8 on 2025-10-20 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_shelf'),
        ('manufacture', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgoodsreadyfromproduction',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.location'),
        ),
        migrations.AddField(
            model_name='finishedgoodsreadyfromproduction',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
    ]
