# Generated by Django 5.1.8 on 2025-10-21 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0003_finishedgoodsreadyfromproduction_location_and_more'),
        ('purchase', '0020_purchaseorderitem_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturequalitycontrol',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.batch'),
        ),
        migrations.AddField(
            model_name='receivefinishedgoods',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.batch'),
        ),
    ]
