# Generated by Django 5.1.8 on 2025-10-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0005_finishedgoodsreadyfromproduction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgoodsreadyfromproduction',
            name='product_type',
            field=models.CharField(choices=[('raw_materials', 'raw_materials'), ('finished_product', 'finished_roduct'), ('component', 'component'), ('BOM', 'BOM')], default='finished product', max_length=50),
        ),
        migrations.AddField(
            model_name='manufacturequalitycontrol',
            name='product_type',
            field=models.CharField(choices=[('raw_materials', 'raw_materials'), ('finished_product', 'finished_roduct'), ('component', 'component'), ('BOM', 'BOM')], default='finished product', max_length=50),
        ),
        migrations.AddField(
            model_name='materialsdeliveryitem',
            name='product_type',
            field=models.CharField(choices=[('raw_materials', 'raw_materials'), ('finished_product', 'finished_roduct'), ('component', 'component'), ('BOM', 'BOM')], default='finished product', max_length=50),
        ),
        migrations.AddField(
            model_name='materialsrequestitem',
            name='product_type',
            field=models.CharField(choices=[('raw_materials', 'raw_materials'), ('finished_product', 'finished_roduct'), ('component', 'component'), ('BOM', 'BOM')], default='finished product', max_length=50),
        ),
        migrations.AddField(
            model_name='receivefinishedgoods',
            name='product_type',
            field=models.CharField(choices=[('raw_materials', 'raw_materials'), ('finished_product', 'finished_roduct'), ('component', 'component'), ('BOM', 'BOM')], default='finished product', max_length=50),
        ),
    ]
