# Generated by Django 5.1.8 on 2025-04-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDispatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_id', models.CharField(blank=True, max_length=20, null=True)),
                ('dispatch_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('IN_PROCESS', 'In Process'), ('READY_FOR_QC', 'Ready for QC'), ('DISPATCHED', 'Dispatched'), ('ON_BOARD', 'On Board'), ('IN_TRANSIT', 'In Transit'), ('CUSTOM_CLEARANCE_IN_PROCESS', 'Custom Clearance In Process'), ('REACHED', 'Reached'), ('OBI', 'OBI done'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='IN_PROCESS', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('carrier', models.CharField(max_length=100)),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('estimated_delivery', models.DateField()),
                ('status', models.CharField(choices=[('IN_PROCESS', 'In Process'), ('READY_FOR_QC', 'Ready for QC'), ('DISPATCHED', 'Dispatched'), ('ON_BOARD', 'On Board'), ('IN_TRANSIT', 'In Transit'), ('CUSTOM_CLEARANCE_IN_PROCESS', 'Custom Clearance In Process'), ('REACHED', 'Reached'), ('OBI', 'OBI done'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleDispatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_id', models.CharField(blank=True, max_length=20, null=True)),
                ('unit_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dispatch_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('IN_PROCESS', 'In Process'), ('READY_FOR_DISPATCH', 'Ready for Dispatch'), ('DISPATCHED', 'Dispatched'), ('ON_BOARD', 'On Board'), ('IN_TRANSIT', 'In Transit'), ('CUSTOM_CLEARANCE_IN_PROCESS', 'Custom Clearance In Process'), ('REACHED', 'Reached'), ('OBI', 'OBI done'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='IN_PROCESS', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('carrier', models.CharField(max_length=100)),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('estimated_delivery', models.DateField()),
                ('status', models.CharField(choices=[('IN_PROCESS', 'In Process'), ('READY_FOR_DISPATCH', 'Ready for Dispatch'), ('DISPATCHED', 'Dispatched'), ('ON_BOARD', 'On Board'), ('IN_TRANSIT', 'In Transit'), ('CUSTOM_CLEARANCE_IN_PROCESS', 'Custom Clearance In Process'), ('REACHED', 'Reached'), ('OBI', 'OBI done'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
