# Generated by Django 5.1.8 on 2025-04-14 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('logistics', '0001_initial'),
        ('purchase', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedispatchitem',
            name='dispatch_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_dispatch_item', to='purchase.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='purchasedispatchitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseshipment',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_shipment', to='purchase.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseshipment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_shipment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasedispatchitem',
            name='purchase_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_dispatch_item', to='logistics.purchaseshipment'),
        ),
        migrations.AddField(
            model_name='saledispatchitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_sale_dispatch', to='purchase.batch'),
        ),
        migrations.AddField(
            model_name='saledispatchitem',
            name='dispatch_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_dispatch_item', to='sales.saleorderitem'),
        ),
        migrations.AddField(
            model_name='saledispatchitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_location', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='saledispatchitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saledispatchitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_warehouse', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='saleshipment',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_shipment', to='sales.saleorder'),
        ),
        migrations.AddField(
            model_name='saleshipment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_shipment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saledispatchitem',
            name='sale_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_shipment_dispatch', to='logistics.saleshipment'),
        ),
    ]
