# Generated by Django 5.1.8 on 2025-10-17 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_purchasedispatchitem_batch'),
        ('purchase', '0020_purchaseorderitem_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedispatchitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_dispatch_item_batch', to='purchase.batch'),
        ),
    ]
