# Generated by Django 5.1.8 on 2025-10-02 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('failure_audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('welcome_message', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('account_create_success', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('request_for_logged_in', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('logged_in_success', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('forget_password', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('order_placed_success', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('hold_on_message', models.FileField(blank=True, null=True, upload_to='audio/')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_quality', models.IntegerField(choices=[('', 'Select an option'), (1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('payment_quality', models.IntegerField(choices=[('', 'Select an option'), (1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('communication_quality', models.IntegerField(choices=[('', 'Select an option'), (1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('product_quality', models.IntegerField(choices=[('', 'Select an option'), (1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_text', models.TextField(blank='', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_review_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.IntegerField()),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='review_images/')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='review_images/')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='review_images/')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='review_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
