# Generated by Django 5.1.8 on 2025-10-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('raw_materials', 'raw_materials'), ('finished_product', 'finished_product'), ('component', 'component'), ('BOM', 'BOM')], default='finished product', max_length=50),
        ),
    ]
