# Generated by Django 5.1.8 on 2025-10-20 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
        ('finance', '0003_purchaseinvoice_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_customer', to='customer.customer'),
        ),
    ]
