# Generated by Django 5.1.8 on 2025-10-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_directinvoice_directinvoiceitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directinvoiceitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='directpurchaseinvoiceitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
