# Generated by Django 5.1.8 on 2025-10-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_directinvoiceitem_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directinvoice',
            name='document_type',
            field=models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('quotation', 'Quotation'), ('factory_out', 'Factory out')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='directinvoiceitem',
            name='usage_purpose',
            field=models.CharField(blank=True, choices=[('sale', 'Sold to Customer'), ('factory', 'Consumed in Factory')], help_text='Defines if this line item is sold or consumed in factory.', max_length=20, null=True),
        ),
    ]
