# Generated by Django 5.1.8 on 2025-10-29 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_directinvoice_document_type_and_more'),
        ('product', '0003_alter_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='directinvoiceitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_invoice_categories', to='product.category'),
        ),
        migrations.AddField(
            model_name='directpurchaseinvoiceitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_purchase_invoice_categories', to='product.category'),
        ),
    ]
