# Generated by Django 5.1.8 on 2025-10-29 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_directinvoiceitem_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directinvoiceitem',
            old_name='item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='directpurchaseinvoiceitem',
            old_name='item',
            new_name='product',
        ),
    ]
