# Generated by Django 5.1.8 on 2025-10-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_rename_item_directinvoiceitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directinvoiceitem',
            name='confirmed_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='directpurchaseinvoiceitem',
            name='confirmed_quantity',
            field=models.FloatField(default=0),
        ),
    ]
