# Generated by Django 5.1.8 on 2025-10-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_directinvoiceitem_confirmed_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directinvoice',
            name='terms_and_conditions',
            field=models.TextField(blank=True, help_text='Write custom terms & conditions for this invoice', null=True),
        ),
        migrations.AddField(
            model_name='directpurchaseinvoice',
            name='terms_and_conditions',
            field=models.TextField(blank=True, help_text='Write custom terms & conditions for this invoice', null=True),
        ),
    ]
