# Generated by Django 5.1.8 on 2025-10-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_directinvoice_terms_and_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('UPDATED', 'Updated'), ('PAID', 'Paid')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='directpurchaseinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('UPDATED', 'Updated'), ('PAID', 'Paid')], default='DRAFT', max_length=20),
        ),
    ]
