# Generated by Django 5.1.8 on 2025-04-14 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('logistics', '0002_initial'),
        ('product', '0001_initial'),
        ('purchase', '0001_initial'),
        ('supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_supplier', to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_purchase_order_item', to='purchase.batch'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepared_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='product.product'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_item', to='purchase.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_item_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_item', to='product.product'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_item_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='order_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_request_item', to='purchase.purchaserequestitem'),
        ),
        migrations.AddField(
            model_name='purchaserequestorder',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequestorder',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requester_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequestorder',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequestorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='purchase_request_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_order', to='purchase.purchaserequestorder'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_request_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_request_order', to='purchase.purchaserequestorder'),
        ),
        migrations.AddField(
            model_name='qualitycontrol',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qc_product', to='product.product'),
        ),
        migrations.AddField(
            model_name='qualitycontrol',
            name='purchase_dispatch_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_control', to='logistics.purchasedispatchitem'),
        ),
        migrations.AddField(
            model_name='qualitycontrol',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_control_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receivegoods',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_goods_location', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='receivegoods',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='receivegoods',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_goods', to='purchase.purchaseorder'),
        ),
        migrations.AddField(
            model_name='receivegoods',
            name='quality_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_goods', to='purchase.qualitycontrol'),
        ),
        migrations.AddField(
            model_name='receivegoods',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_goods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receivegoods',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_goods_warehouse', to='inventory.warehouse'),
        ),
    ]
