# Generated by Django 5.1.8 on 2025-10-05 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_batch_barcode_batch_barcode_image_batch_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_quotations', to='purchase.supplierquotation'),
        ),
    ]
