# Generated by Django 5.1.8 on 2025-10-05 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_purchaseorder_supplier_quotation'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_items_supplier', to='supplier.supplier'),
        ),
    ]
