# Generated by Django 5.1.8 on 2025-10-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_purchaseorderitem_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierquotation',
            name='AIT_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='AIT_type',
            field=models.CharField(blank=True, choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='VAT_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='VAT_type',
            field=models.CharField(blank=True, choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='ait_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='net_due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
