# Generated by Django 5.1.8 on 2025-10-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_supplierquotation_ait_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierquotationitem',
            old_name='ait_status',
            new_name='AIT_type',
        ),
        migrations.RenameField(
            model_name='supplierquotationitem',
            old_name='vat_percentage',
            new_name='VAT_rate',
        ),
        migrations.RenameField(
            model_name='supplierquotationitem',
            old_name='vat_status',
            new_name='VAT_type',
        ),
        migrations.AlterField(
            model_name='supplierquotation',
            name='AIT_type',
            field=models.CharField(blank=True, choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], default='exclusive', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplierquotation',
            name='VAT_type',
            field=models.CharField(blank=True, choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], default='exclusive', max_length=50, null=True),
        ),
    ]
