# Generated by Django 5.1.8 on 2025-10-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_rename_ait_status_supplierquotationitem_ait_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='AIT_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='AIT_type',
            field=models.CharField(blank=True, choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], default='exclusive', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='VAT_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='VAT_type',
            field=models.CharField(blank=True, choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], default='exclusive', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ait_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
