# Generated by Django 5.1.8 on 2025-10-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_purchaseorder_ait_rate_purchaseorder_ait_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaserequestitem',
            old_name='total_price',
            new_name='unit_price',
        ),
    ]
