# Generated by Django 5.1.8 on 2025-10-14 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_rename_total_price_purchaserequestitem_unit_price'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_order_item_supplier', to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
