# Generated by Django 5.1.8 on 2025-10-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_purchaserequestorder_supplier'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='suppliers',
            field=models.ManyToManyField(related_name='supplier_rfqs', to='supplier.supplier'),
        ),
    ]
