# Generated by Django 5.1.8 on 2025-10-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_purchaseorder_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
