# Generated by Django 5.1.8 on 2025-10-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_rfqitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
