# Generated by Django 5.1.8 on 2025-10-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0016_alter_purchaserequestitem_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierquotationitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
