# Generated by Django 5.1.8 on 2025-10-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0017_supplierquotationitem_vat_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierquotation',
            name='currency',
            field=models.CharField(default='BDT', max_length=10),
        ),
    ]
