# Generated by Django 5.1.8 on 2025-10-22 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_unit'),
        ('purchase', '0020_purchaseorderitem_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_batch', to='purchase.batch'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_categories', to='product.category'),
        ),
        migrations.AddField(
            model_name='qualitycontrol',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.batch'),
        ),
    ]
