# Generated by Django 5.1.8 on 2025-10-26 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0021_purchaserequestitem_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierquotationitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.batch'),
        ),
    ]
