# Generated by Django 5.1.8 on 2025-10-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0022_supplierquotationitem_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product_type',
            field=models.CharField(choices=[('raw_materials', 'raw_materials'), ('finished_product', 'finished_roduct'), ('component', 'component'), ('BOM', 'BOM')], default='finished product', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='product_type',
            field=models.CharField(choices=[('raw_materials', 'raw_materials'), ('finished_product', 'finished_roduct'), ('component', 'component'), ('BOM', 'BOM')], default='finished product', max_length=50),
        ),
        migrations.AddField(
            model_name='receivegoods',
            name='product_type',
            field=models.CharField(choices=[('raw_materials', 'raw_materials'), ('finished_product', 'finished_roduct'), ('component', 'component'), ('BOM', 'BOM')], default='finished product', max_length=50),
        ),
        migrations.AddField(
            model_name='rfqitem',
            name='product_type',
            field=models.CharField(choices=[('raw_materials', 'raw_materials'), ('finished_product', 'finished_roduct'), ('component', 'component'), ('BOM', 'BOM')], default='finished product', max_length=50),
        ),
        migrations.AddField(
            model_name='supplierquotationitem',
            name='product_type',
            field=models.CharField(choices=[('raw_materials', 'raw_materials'), ('finished_product', 'finished_roduct'), ('component', 'component'), ('BOM', 'BOM')], default='finished product', max_length=50),
        ),
    ]
