# Generated by Django 5.1.8 on 2025-08-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='biometrict_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo_id',
            field=models.ImageField(blank=True, null=True, upload_to='user_photo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('CEO', 'CEO'), ('CFO', 'CFO'), ('CMO', 'CMO'), ('CTO', 'CTO'), ('director', 'director'), ('general_manager', 'Geberal Manager'), ('manager', 'Manager'), ('team_lead', 'Team Lead'), ('employee', 'Employee'), ('intern', 'Intern'), ('hr', 'HR'), ('finance', 'Finance'), ('it_support', 'IT Support'), ('guest', 'Guest/User')], default='patient', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
