# Generated by Django 5.1.8 on 2025-10-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_phoneotp_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('CEO', 'CEO'), ('CFO', 'CFO'), ('CMO', 'CMO'), ('CTO', 'CTO'), ('director', 'director'), ('general_manager', 'Geberal Manager'), ('manager', 'Manager'), ('team_lead', 'Team Lead'), ('employee', 'Employee'), ('intern', 'Intern'), ('hr', 'HR'), ('finance', 'Finance'), ('it_support', 'IT Support'), ('guest', 'Guest/User'), ('customer', 'Customer'), ('corporate-user', 'Corporate User'), ('job-seeker', 'Job seeker'), ('employee', 'Employee')], default='patient', max_length=15),
        ),
    ]
