# Generated by Django 5.1.8 on 2025-10-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_biometrict_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('corporate-user', 'Corporate User'), ('job-seeker', 'Job seeker'), ('employee', 'Employee'), ('superadmin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager')], default='patient', max_length=15),
        ),
    ]
