# Generated by Django 5.1.8 on 2025-10-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('forgot_password', 'Forgot Password'), ('change_password', 'Change Password')], default='registration', max_length=20),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
