# Generated by Django 5.1.8 on 2025-10-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_phoneotp_purpose_alter_phoneotp_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
