# Generated by Django 5.1.8 on 2025-10-27 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_phoneotp_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneotp',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
        ),
    ]
