# Generated by Django 5.1.8 on 2025-10-27 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_directinvoice_directinvoiceitem_and_more'),
        ('inventory', '0003_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='direct_purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_purchase_invoice', to='finance.directpurchaseinvoice'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='direct_sale_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_invoice', to='finance.directinvoice'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('MANUFACTURE_IN', 'Manufacture IN'), ('MANUFACTURE_OUT', 'Manufacture OUT'), ('REPLACEMENT_OUT', 'Replacement Out'), ('REPLACEMENT_IN', 'Replacement In'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In'), ('EXISTING_ITEM_IN', 'Existing items'), ('OPERATIONS_OUT', 'Operations out'), ('SCRAPPED_OUT', 'Scrapped out'), ('SCRAPPED_IN', 'Scrapped in'), ('DIRECT_SALE_OUT', 'Direct invoice out'), ('DIRECT_PURCHASE_IN', 'Direct Purchase IN')], max_length=20, null=True),
        ),
    ]
