# Generated by Django 5.1.8 on 2025-10-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventorytransaction_direct_purchase_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='product_type',
            field=models.CharField(blank=True, choices=[('raw_materials', 'raw_materials'), ('finished_product', 'finished_product'), ('component', 'component'), ('BOM', 'BOM')], max_length=50, null=True),
        ),
    ]
