# Generated by Django 5.1.8 on 2025-10-29 01:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorytransaction_product_type'),
        ('product', '0003_alter_product_product_type'),
        ('purchase', '0023_purchaseorderitem_product_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('warehouse', 'location', 'product'), name='unique_inventory_per_location'),
        ),
    ]
