# Generated by Django 5.1.8 on 2025-11-01 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventory_unique_inventory_per_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelf_inventory', to='inventory.shelf'),
        ),
    ]
