# Generated by Django 5.1.8 on 2025-04-14 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=20)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ADDED', 'Added into stock'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationsDeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=20)),
                ('item_type', models.CharField(choices=[('PRODUCT', 'Product'), ('COMPONENT', 'Component')], max_length=10)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(blank=True, choices=[('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationsRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=20, unique=True)),
                ('purpose', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20)),
                ('status', models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationsRequestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True)),
                ('approval_status', models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approval_data', models.JSONField(blank=True, default=dict, null=True)),
                ('requester_approval_status', models.CharField(blank=True, max_length=20, null=True)),
                ('reviewer_approval_status', models.CharField(blank=True, max_length=20, null=True)),
                ('approver_approval_status', models.CharField(blank=True, max_length=20, null=True)),
                ('Requester_remarks', models.TextField(blank=True, null=True)),
                ('Reviewer_remarks', models.TextField(blank=True, null=True)),
                ('Approver_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('can_request', 'can request'), ('can_review', 'Can review'), ('can_approve', 'Can approve')],
            },
        ),
        migrations.CreateModel(
            name='ExistingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ADDED', 'Added into stock'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_order_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_request', 'can request'), ('can_review', 'Can review'), ('can_approve', 'Can approve')],
            },
        ),
    ]
