# Generated by Django 5.1.8 on 2025-04-14 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('operations', '0001_initial'),
        ('product', '0001_initial'),
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='existingorderitems',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_existing_item', to='purchase.batch'),
        ),
        migrations.AddField(
            model_name='existingorderitems',
            name='existing_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_existing_order_items', to='operations.existingorder'),
        ),
        migrations.AddField(
            model_name='existingorderitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_order_product', to='product.product'),
        ),
        migrations.AddField(
            model_name='existingorderitems',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_order_items_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationsdeliveryitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_operation_delivery_item', to='purchase.batch'),
        ),
        migrations.AddField(
            model_name='operationsdeliveryitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.location'),
        ),
        migrations.AddField(
            model_name='operationsdeliveryitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_product_item_delivery', to='product.product'),
        ),
        migrations.AddField(
            model_name='operationsdeliveryitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationsdeliveryitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='operationsrequestitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_operation_request_item', to='purchase.batch'),
        ),
        migrations.AddField(
            model_name='operationsrequestitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_product_request', to='product.product'),
        ),
        migrations.AddField(
            model_name='operationsrequestitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationsdeliveryitem',
            name='operations_request_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_request_items_delivery', to='operations.operationsrequestitem'),
        ),
        migrations.AddField(
            model_name='operationsrequestorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationsrequestitem',
            name='operations_request_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_request_items', to='operations.operationsrequestorder'),
        ),
        migrations.AddField(
            model_name='operationsdeliveryitem',
            name='operations_request_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_request_order_delivery', to='operations.operationsrequestorder'),
        ),
    ]
