# Generated by Django 5.1.8 on 2025-10-22 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_initial'),
        ('product', '0002_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='existingorderitems',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='existing_category_request', to='product.product'),
        ),
        migrations.AddField(
            model_name='operationsdeliveryitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_categories_delivery', to='product.product'),
        ),
        migrations.AddField(
            model_name='operationsrequestitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_category_request', to='product.product'),
        ),
    ]
