# Generated by Django 5.1.8 on 2025-10-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_existingorderitems_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='existingorderitems',
            name='product_type',
            field=models.CharField(choices=[('raw_materials', 'raw_materials'), ('finished_product', 'finished_roduct'), ('component', 'component'), ('BOM', 'BOM')], default='finished product', max_length=50),
        ),
        migrations.AddField(
            model_name='operationsdeliveryitem',
            name='product_type',
            field=models.CharField(choices=[('raw_materials', 'raw_materials'), ('finished_product', 'finished_roduct'), ('component', 'component'), ('BOM', 'BOM')], default='finished product', max_length=50),
        ),
        migrations.AddField(
            model_name='operationsrequestitem',
            name='product_type',
            field=models.CharField(choices=[('raw_materials', 'raw_materials'), ('finished_product', 'finished_roduct'), ('component', 'component'), ('BOM', 'BOM')], default='finished product', max_length=50),
        ),
    ]
