# Generated by Django 5.1.8 on 2025-10-28 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_existingorderitems_product_type_and_more'),
        ('product', '0003_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationsdeliveryitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_categories_delivery', to='product.category'),
        ),
    ]
