# Generated by Django 5.1.8 on 2025-10-03 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('CARRY_FORWARD', 'Carry Forward Leave'), ('MONTHLY_ACCRUAL', 'Monthly Leave Accrual'), ('LATE_DEDUCTION', 'Late Leave Deduction')], max_length=50)),
                ('run_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('job_type', 'run_date')},
            },
        ),
    ]
