# Generated by Django 5.1.8 on 2026-01-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanagement', '0002_leavejoblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
