# Generated by Django 5.1.8 on 2025-04-14 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('officemanagement', '0001_initial'),
        ('supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stationarypurchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='stationarypurchaseorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stationarypurchaseitem',
            name='stationary_purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stationary_request_order', to='officemanagement.stationarypurchaseorder'),
        ),
        migrations.AddField(
            model_name='stationaryinventorytransaction',
            name='stationary_purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stationary_purchase_transactions', to='officemanagement.stationarypurchaseorder'),
        ),
        migrations.AddField(
            model_name='stationaryusagerequestitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_usage', to='officemanagement.stationarybatch'),
        ),
        migrations.AddField(
            model_name='stationaryusagerequestitem',
            name='stationary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='officemanagement.stationarycategory'),
        ),
        migrations.AddField(
            model_name='stationaryusagerequestitem',
            name='stationary_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officemanagement.stationaryproduct'),
        ),
        migrations.AddField(
            model_name='stationaryusagerequestitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stationaryusagerequestorder',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AddField(
            model_name='stationaryusagerequestorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stationaryusagerequestitem',
            name='stationary_usage_request_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_order', to='officemanagement.stationaryusagerequestorder'),
        ),
        migrations.AddField(
            model_name='stationaryinventorytransaction',
            name='stationary_usage_request_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stationary_usage_transactions', to='officemanagement.stationaryusagerequestorder'),
        ),
        migrations.AddField(
            model_name='visitorgroup',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Please choose company to add member if any', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='officemanagement.visitorgroup'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='meetingroombooking',
            unique_together={('room', 'date', 'start_time', 'end_time')},
        ),
        migrations.AlterUniqueTogether(
            name='expensesubmissionorder',
            unique_together={('advance_ref',)},
        ),
    ]
