# Generated by Django 5.1.8 on 2025-10-09 04:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officemanagement', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('lost', 'Lost'), ('expired', 'Expired')], default='active', max_length=20)),
                ('printed', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='visitor_qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='id_card',
            field=models.ForeignKey(blank=True, help_text='Select the ID card issued to this visitor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_visitors', to='officemanagement.visitoridcard'),
        ),
    ]
