# Generated by Django 5.1.8 on 2025-10-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officemanagement', '0003_visitoridcard_visitorlog_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitoridcard',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('lost', 'Lost'), ('expired', 'Expired'), ('idle', 'Idle'), ('in_use', 'In Use')], default='active', max_length=20),
        ),
    ]
