# Generated by Django 5.1.8 on 2025-10-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officemanagement', '0004_alter_visitoridcard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesubmissionorder',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
