# Generated by Django 5.1.8 on 2025-10-11 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officemanagement', '0007_alter_expensesubmissionorder_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationarypurchaseitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='officemanagement.stationarybatch'),
        ),
    ]
