# Generated by Django 5.1.8 on 2025-10-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_customerquotation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
