# Generated by Django 5.1.8 on 2025-10-14 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_saleorder_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerequestorder',
            name='customer_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_sales_quotation', to='sales.customerquotation'),
        ),
    ]
