# Generated by Django 5.1.8 on 2025-10-18 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
        ('sales', '0004_alter_salerequestorder_customer_quotation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerquotationitem',
            old_name='vat_percentage',
            new_name='VAT_rate',
        ),
        migrations.RemoveField(
            model_name='customerquotationitem',
            name='ait_status',
        ),
        migrations.RemoveField(
            model_name='customerquotationitem',
            name='vat_status',
        ),
        migrations.AddField(
            model_name='customerquotation',
            name='AIT_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overall AIT (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customerquotation',
            name='AIT_type',
            field=models.CharField(blank=True, choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], default='exclusive', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerquotation',
            name='ait_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='customerquotation',
            name='currency',
            field=models.CharField(default='BDT', max_length=10),
        ),
        migrations.AddField(
            model_name='customerquotation',
            name='net_due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='customerquotation',
            name='quoted_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerquotation',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='customerquotation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='customerquotation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_quotation_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerquotation',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='customerquotationitem',
            name='VAT_type',
            field=models.CharField(choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], default='exclusive', max_length=20),
        ),
        migrations.AddField(
            model_name='customerquotationitem',
            name='currency',
            field=models.CharField(default='BDT', max_length=10),
        ),
        migrations.AddField(
            model_name='customerquotationitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerquotationitem',
            name='quoted_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerquotationitem',
            name='specification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerquotationitem',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerquotationitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='AIT_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overall AIT (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='AIT_type',
            field=models.CharField(blank=True, choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], default='exclusive', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='ait_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='currency',
            field=models.CharField(default='BDT', max_length=10),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='net_due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='VAT_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='VAT_type',
            field=models.CharField(choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], default='exclusive', max_length=20),
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='currency',
            field=models.CharField(default='BDT', max_length=10),
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='quoted_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='specification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salerequestitem',
            name='VAT_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salerequestitem',
            name='VAT_type',
            field=models.CharField(choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], default='exclusive', max_length=20),
        ),
        migrations.AddField(
            model_name='salerequestitem',
            name='currency',
            field=models.CharField(default='BDT', max_length=10),
        ),
        migrations.AddField(
            model_name='salerequestitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salerequestitem',
            name='quoted_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salerequestitem',
            name='specification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salerequestitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salerequestitem',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salerequestitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='salerequestitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salerequestorder',
            name='AIT_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overall AIT (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='salerequestorder',
            name='AIT_type',
            field=models.CharField(blank=True, choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], default='exclusive', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salerequestorder',
            name='ait_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salerequestorder',
            name='currency',
            field=models.CharField(default='BDT', max_length=10),
        ),
        migrations.AddField(
            model_name='salerequestorder',
            name='net_due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='salerequestorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salerequestorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salerequestorder',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='customerquotation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_quotation_customers', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='customerquotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerquotationitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customerquotationitem',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_quotation_items', to='sales.customerquotation'),
        ),
        migrations.AlterField(
            model_name='customerquotationitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='customerquotationitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
