# Generated by Django 5.1.8 on 2025-10-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
        ('sales', '0005_rename_vat_percentage_customerquotationitem_vat_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerquotation',
            name='customer',
        ),
        migrations.AddField(
            model_name='customerquotation',
            name='customers',
            field=models.ManyToManyField(related_name='sales_quotation_customers', to='customer.customer'),
        ),
    ]
