# Generated by Django 5.1.8 on 2025-10-20 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_customerquotation_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerquotation',
            old_name='customers',
            new_name='customer',
        ),
    ]
