# Generated by Django 5.1.8 on 2025-10-20 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
        ('sales', '0007_rename_customers_customerquotation_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerquotation',
            name='customer',
        ),
        migrations.AddField(
            model_name='customerquotation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_quotation_customers', to='customer.customer'),
        ),
    ]
