# Generated by Django 5.1.8 on 2025-10-22 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_unit'),
        ('purchase', '0021_purchaserequestitem_batch_and_more'),
        ('sales', '0008_remove_customerquotation_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerquotationitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_quotation_batches', to='purchase.batch'),
        ),
        migrations.AddField(
            model_name='customerquotationitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.AddField(
            model_name='salerequestitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
