# Generated by Django 5.1.8 on 2025-10-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_customerquotationitem_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerquotationitem',
            name='product_type',
            field=models.CharField(choices=[('raw_materials', 'raw_materials'), ('finished_product', 'finished_roduct'), ('component', 'component'), ('BOM', 'BOM')], default='finished product', max_length=50),
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='product_type',
            field=models.CharField(choices=[('raw_materials', 'raw_materials'), ('finished_product', 'finished_roduct'), ('component', 'component'), ('BOM', 'BOM')], default='finished product', max_length=50),
        ),
        migrations.AddField(
            model_name='salequalitycontrol',
            name='product_type',
            field=models.CharField(choices=[('raw_materials', 'raw_materials'), ('finished_product', 'finished_roduct'), ('component', 'component'), ('BOM', 'BOM')], default='finished product', max_length=50),
        ),
        migrations.AddField(
            model_name='salerequestitem',
            name='product_type',
            field=models.CharField(choices=[('raw_materials', 'raw_materials'), ('finished_product', 'finished_roduct'), ('component', 'component'), ('BOM', 'BOM')], default='finished product', max_length=50),
        ),
    ]
