# Generated by Django 5.1.8 on 2025-04-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id', models.CharField(max_length=30)),
                ('is_work_completed', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Is Work Completed?')),
                ('progress', models.CharField(blank=True, choices=[('PROGRESS-20%', 'Progress 20%'), ('PROGRESS-30%', 'Progress 30%'), ('PROGRESS-40%', 'Progress 40%'), ('PROGRESS-50%', 'Progress 50%'), ('PROGRESS-60%', 'Progress 60%'), ('PROGRESS-70%', 'Progress 70%'), ('PROGRESS-80%', 'Progress 80%'), ('PROGRESS-90%', 'Progress 90%'), ('PROGRESS-100%', 'Progress 100%')], max_length=100, null=True)),
                ('work_quality_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('communication_quality_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('timely_completion_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('behavoiural_quality_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('product_quality', models.FloatField(blank=True, default=0.0, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='repair_return')),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
